# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Homepage"
email: "yw590@cam.ac.uk"
description: "PhD student in Theoretical and Applied Linguistics, Phonetics and Phonology Lab, University of Cambridge"
baseurl: ""  # Don't change this
url: "https://yutongfwang.github.io"  # Updated to match renamed repo
minimal_mistakes_skin: default
search: true
mathjax: true

# Author info
author:
  name   : "Yutong (Felicia) Wang"
  avatar : "/assets/images/IMG_4017.jpg"
  bio    : "PhD student in Theoretical and Applied Linguistics at the University of Cambridge."
  location: "Cambridge, UK"
  links:
    - label: "Lab Profile"
      icon: "fas fa-fw fa-university"
      url: "https://www.phonetics.mmll.cam.ac.uk/staff/yutong-wang"
     - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://uk.linkedin.com/in/yutong-wang-8046b1233"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://x.com/ythun_wan?s=11&t=tl8HBKumDgpecXsLPgGgnQ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/YutongFWang"

# Footer links
footer:
  links:
    - label: "Lab Profile"
      icon: "fas fa-fw fa-university"
      url: "https://www.phonetics.mmll.cam.ac.uk/staff/yutong-wang"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://x.com/ythun_wan?s=11&t=tl8HBKumDgpecXsLPgGgnQ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/YutongFWang"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/London

# Content structure
include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
